### ISSUE TITLE
Is any pretrained model available for direct use ?

### ISSUE THREAD

**Issue by JigyassaLamba** [abhilash1910/LongPegasus#1]
Please specify the usage instructions of the model. How can I test directly using pretrained model?

**Comment by abhilash1910** [comment]
Hi @JigyassaLamba ,
I have updated the readme for your reference. The latest [module (version 0.2)](https://github.com/abhilash1910/LongPegasus#using-the-latest-version-02) provides a walkthrough how you can use any pretrained pegasus models present on huggingface hub  for creating a longer version of it . 
You can use the stored long model created through this package for finetuning as well (however havent added any demos on that yet). The backend uses tf and hence for inference it is important to specify return_tensors as tf.
